packages:
  - "apps/*"
  - "apps/*/*"
  - "packages/*"
  - "tests/*"
  - "!**/bundle"
  - "!**/bundle/**"
  - "!**/bundle-old"
  - "!**/bundle-old/**"
  - "!**/dist"
  - "!**/dist/**"
  - "!**/dist-old"
  - "!**/dist-old/**"
  - "!**/release"
  - "!**/release/**"
  - "!**/release-old"
  - "!**/release-old/**"
  - "!**/node_modules"
  - "!**/node_modules/**"
